<?php return array (
  'USE_DATABASE' => 'mysql',
  'USE_COMMAND' => true,
  'USE_SESSION' => true,
  'MYSQL_HOST' => 'localhost',
  'MYSQL_USER' => 'root',
  'MYSQL_PASSWORD' => 'callofduty321',
  'MYSQL_DATABASE' => 'test',
  'MYSQL_PORT' => '3306',
  'MYSQL_CHARSET' => 'utf8',
  'MSSQL_HOST' => 'localhost',
  'MSSQL_USER' => 'root',
  'MSSQL_PASSWORD' => '123',
  'MSSQL_DATABASE' => 'test',
  'MSSQL_PORT' => '1433',
  'MSSQL_CHARSET' => 'utf8',
  'SQLITE_FILE' => 'xxx.db',
  'REDIS_DRIVER' => 'predis',
  'REDIS_HOST' => '127.0.0.1',
  'REDIS_PORT' => '6379',
);